name: smart_ojak
description: "Smart home application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  app_ui:
    path: packages/app_ui
  data_provider: 
    path: packages/data_provider
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  auto_size_text: ^3.0.0
  equatable: ^2.0.7
  talker_flutter: ^4.9.1
  talker_bloc_logger: ^4.9.1
  talker: ^4.9.1
  get_it: ^8.0.3

  auto_route: ^10.0.1
  cupertino_icons: ^1.0.8
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  hydrated_bloc: ^10.0.0
  flutter_gen: ^5.10.0
  another_flutter_splash_screen: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  hive_ce_generator: ^1.9.2
  bloc_lint: 0.2.0-dev.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

    