name: app_ui
description: App UI Component Library.
version: 0.0.3

publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # assets:
  #   - assets/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Black.otf
  #         weight: 900
  #       - asset: assets/fonts/Inter-ExtraBold.otf
  #         weight: 800
  #       - asset: assets/fonts/Inter-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/Inter-SemiBold.otf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Light-BETA.otf
  #         weight: 300
  #       - asset: assets/fonts/Inter-ExtraLight-BETA.otf
  #         weight: 200
  #       - asset: assets/fonts/Inter-Thin-BETA.otf
  #         weight: 100
